### ISSUE TITLE
Alternatives to `ps2ascii`

### ISSUE THREAD

**Issue by natsukagami** [curvegrid/parse-uw-coop-package#2]
Currently, I think `ps2ascii` works for most applications. However, upon manual inspections, I find that it outputs very chaotic output with lots of whitespaces. Longer output = longer regexp matching time. Furthermore, information hidden behind hyperlinks (for example, the [famous AwesomeCV's](https://github.com/posquit0/Awesome-CV/blob/master/examples/resume.pdf) header) cannot be parsed. 

I know some of the alternatives to `ps2ascii`, both are available in the `poppler` package available to both Linux (on many distro's default repositories) and MacOS (with Homebrew):
 - `pdftotext`: It renders text out of the PDF file. I tried it on my resume and some templates on Overleaf, and it seems to get the same output as with `ps2ascii`. However the output is much smaller, so the matching time is much faster.
 - `pdftohtml`: Basically it outputs HTML, so words sometimes are harder to parse out (it also aggressively outputs `&#160;` instead of a single space!) But it works perfectly when parsing hyperlinks. The output is also smaller than with `ps2ascii`, even with all the HTML.

EDIT: typo

**Comment by shoenseiwaso** [comment]
Resolved by switching to `pdftotext` in #3
